PortfolioProject-3/Controllers/SocialMediaController.cs
using Microsoft.AspNetCore.Mvc;
using PortfolioProject_3.DataAccess.Context;
using PortfolioProject_3.DataAccess.Entities;

namespace PortfolioProject_3.Controllers
{
    public class SocialMediaController : Controller
    {
        private readonly PortfolioContext _context;

        public SocialMediaController(PortfolioContext context)
        {
            _context = context;
        }

        public IActionResult SocialMediaList()
        {
            var values = _context.SocialMedias.ToList();
            return View(values);
        }

        public IActionResult Delete(int id)
        {
            var values = _context.SocialMedias.Find(id);
            _context.SocialMedias.Remove(values);
            _context.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }

        public IActionResult Update(int id)
        {
            var values = _context.SocialMedias.Find(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult Update(SocialMedia socialMedia)
        {
            _context.SocialMedias.Update(socialMedia);
            _context.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }

        public IActionResult Create() => View();

        [HttpPost]
        public IActionResult Create(SocialMedia socialMedia)
        {
            _context.SocialMedias.Add(socialMedia);
            _context.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }
    }
}

PortfolioProject-3/Views/SocialMedia/Create.cshtml
@using PortfolioProject_3.DataAccess.Entities
@model SocialMedia
@{
    ViewData["Title"] = "Sosyal Medya Ekle";
    Layout = "~/Views/Layout/Index.cshtml";
}

<div class="main-panel">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="card shadow-sm">
                        <div class="card-header bg-success text-white">
                            <h4 class="mb-0">Sosyal Medya Ekle</h4>
                        </div>
                        <div class="card-body">
                            <form asp-action="Create" asp-controller="SocialMedia" method="post">
                                <div class="mb-3">
                                    <label class="form-label">Başlık</label>
                                    <input type="text" name="Title" class="form-control" required />
                                </div>

                                <div class="mb-3">
                                    <label class="form-label">Icon</label>
                                    <input type="text" name="Icon" class="form-control" required />
                                </div>

                                <div class="mb-3">
                                    <label class="form-label">Link</label>
                                    <input type="text" name="Url" class="form-control" required />
                                </div>

                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-primary">Kaydet</button>
                                    <a asp-action="SocialMediaList" class="btn btn-secondary">İptal</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProject-3/Views/SocialMedia/SocialMediaList.cshtml
@using PortfolioProject_3.DataAccess.Entities
@model List<SocialMedia>
@{
    ViewData["Title"] = "SocialMediaList";
    Layout = "~/Views/Layout/Index.cshtml";
    int count = 0;
}

<div class="main-panel">
    <div class="content">
        <div class="container-fluid">
            <h4 class="page-title">Sosyal Medya Hesapları</h4>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <table class="table mt-3">
                                <thead>
                                    <tr style="background-color: #C1F0F6;">
                                        <th scope="col">#</th>
                                        <th scope="col">Başlık</th>
                                        <th scope="col">Icon</th>
                                        <th scope="col">Link</th>
                                        <th scope="col">Sil</th>
                                        <th scope="col">Güncelle</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        count++;
                                        <tr>
                                            <td>@count</td>
                                            <td>@item.Title</td>
                                            <td>@item.Icon</td>
                                            <td><a href="@item.Url" target="_blank">@item.Url</a></td>
                                            <td><a href="/SocialMedia/Delete/@item.Id" class="btn btn-danger">Sil</a></td>
                                            <td><a href="/SocialMedia/Update/@item.Id" class="btn btn-success">Güncelle</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <a href="/SocialMedia/Create/" class="btn btn-primary">Sosyal Medya Ekle</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProject-3/Views/SocialMedia/Update.cshtml
@using PortfolioProject_3.DataAccess.Entities
@model SocialMedia
@{
    ViewData["Title"] = "Sosyal Medya Güncelle";
    Layout = "~/Views/Layout/Index.cshtml";
}

<div class="main-panel">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="card shadow-sm">
                        <div class="card-header bg-info text-white">
                            <h4 class="mb-0">Sosyal Medya Güncelle</h4>
                        </div>
                        <div class="card-body">
                            <form asp-action="Update" asp-controller="SocialMedia" method="post">
                                <input type="hidden" name="Id" value="@Model.Id" />

                                <div class="mb-3">
                                    <label class="form-label">Başlık</label>
                                    <input type="text" name="Title" value="@Model.Title" class="form-control" required />
                                </div>

                                <div class="mb-3">
                                    <label class="form-label">Icon</label>
                                    <input type="text" name="Icon" value="@Model.Icon" class="form-control" required />
                                </div>

                                <div class="mb-3">
                                    <label class="form-label">Link</label>
                                    <input type="text" name="Url" value="@Model.Url" class="form-control" required />
                                </div>

                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                    <a asp-action="SocialMediaList" class="btn btn-secondary">İptal</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>